### ISSUE TITLE
TODO fact sheets

### ISSUE THREAD

**Issue by nerik** [Vizzuality/TRASE-frontend#273]
General:
- [ ] Factsheets -> Places
- [ ] Tooltips
- [ ] *Description text: get it from the API*
- [ ] non-hash parameters for the tool page (nodeId, map state)
- [ ] top 3 buttons
- [ ] Dropdowns: add commodity, years, country (only for actors) to URL params + *API endpoint*

Place:
Maps: http://datamaps.github.io/
- [x] world map with country (get TopoJSON, careful with projection)
- [x] biome and state maps (IDs already in endpoint)
- [x] state map: reuse municipalities TopoJSON but isolate state

- [ ] Add dropdowns 
- [ ] 1st table: table selector + *add more tables to API*
- [ ] deforestation trajectory: *mock JSON with several lines (include line styles)*
- [ ] chords diagrams: add interactivity 
- [ ] chord diagrams: *change matrix to have other municipalities in state + find a way to indicate what is the selected node in the matrix*

Actors: 
- [ ] *change tables for lines (reuse place format) + add more lines/countries for the map + map buckets --> for both countries and muncipalities/states/biomes* 
- [ ] extract legend component from Tool page and reuse
- [ ] world map
- [ ] municipalities/states/biomes: extract Tools page map functionality
- [ ] *sustainability table: add*
- [ ] scatter plot
- [ ] scatter plot: *add new type to API + multiple scatter plot selector + mock JSON*

**Comment by nerik** [comment]
Items in *italic* are those that need API changes
